-- ========================================
-- REVIO DATABASE SCHEMA
-- ========================================

CREATE DATABASE "ReviewDB";

-- Connect to ReviewDB before executing
-- the remaining commands.


-- ========================================
-- USERS TABLE
-- ========================================

CREATE TABLE "Users"
(
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "FullName" VARCHAR(100) NOT NULL,
    "Email" TEXT NOT NULL,
    "MobileNumber" VARCHAR(15) NOT NULL,
    "PasswordHash" TEXT NOT NULL,
    "IsEmailVerified" BOOLEAN NOT NULL,
    "Role" VARCHAR(20) NOT NULL DEFAULT 'Reviewer',
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NULL
);


-- ========================================
-- CATEGORIES TABLE
-- ========================================

CREATE TABLE "Categories"
(
    "CategoryId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "CategoryName" TEXT NOT NULL,
    "Icon" TEXT NOT NULL,
    "ImageUrl" TEXT NOT NULL
);


-- ========================================
-- PLACES TABLE
-- ========================================

CREATE TABLE "Places"
(
    "PlaceId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "CategoryId" INTEGER NOT NULL,
    "Address" TEXT NOT NULL,
    "City" TEXT NOT NULL,
    "Rating" DOUBLE PRECISION NOT NULL,
    "ReviewCount" INTEGER NOT NULL,
    "ImageUrl" TEXT NOT NULL,
    "OpenStatus" BOOLEAN NOT NULL
);


-- ========================================
-- BUSINESSES TABLE
-- ========================================

CREATE TABLE "Businesses"
(
    "BusinessId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BusinessName" VARCHAR(150) NOT NULL,
    "Description" VARCHAR(1000) NOT NULL,
    "Address" VARCHAR(500) NOT NULL,
    "City" VARCHAR(100) NOT NULL,
    "Pincode" VARCHAR(20) NOT NULL,
    "PhoneNumber" VARCHAR(20) NOT NULL,
    "Email" VARCHAR(150) NOT NULL,
    "Website" VARCHAR(500) NOT NULL,
    "OpeningTime" VARCHAR(100) NOT NULL,
    "ClosingTime" VARCHAR(100) NOT NULL,
    "Rating" DOUBLE PRECISION NOT NULL,
    "ReviewCount" INTEGER NOT NULL,
    "IsOpen" BOOLEAN NOT NULL,
    "IsActive" BOOLEAN NOT NULL,
    "IsApproved" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "UpdatedAt" TIMESTAMPTZ NULL,
    "CategoryId" INTEGER NOT NULL,
    "OwnerId" INTEGER NOT NULL
);


-- ========================================
-- BUSINESS PHOTOS TABLE
-- ========================================

CREATE TABLE "BusinessPhotos"
(
    "BusinessPhotoId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "BusinessId" INTEGER NOT NULL,
    "PhotoUrl" TEXT NOT NULL,
    "Caption" VARCHAR(200) NOT NULL,
    "IsPrimary" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);


-- ========================================
-- REVIEWS TABLE
-- ========================================

CREATE TABLE "Reviews"
(
    "ReviewId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Rating" INTEGER NOT NULL,
    "Comment" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "OwnerReply" TEXT NULL,
    "OwnerReplyAt" TIMESTAMPTZ NULL,
    "UserId" INTEGER NOT NULL,
    "PlaceId" INTEGER NULL,
    "BusinessId" INTEGER NULL
);


-- ========================================
-- REVIEW MEDIA TABLE
-- ========================================

CREATE TABLE "ReviewMedias"
(
    "ReviewMediaId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ReviewId" INTEGER NOT NULL,
    "MediaUrl" VARCHAR(500) NOT NULL,
    "MediaType" VARCHAR(20) NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);


-- ========================================
-- FAVORITES TABLE
-- ========================================

CREATE TABLE "Favorites"
(
    "FavoriteId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "PlaceId" INTEGER NULL,
    "BusinessId" INTEGER NULL
);


-- ========================================
-- NOTIFICATIONS TABLE
-- ========================================

CREATE TABLE "Notifications"
(
    "NotificationId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Title" TEXT NOT NULL,
    "Message" TEXT NOT NULL,
    "IsRead" BOOLEAN NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL
);


-- ========================================
-- EMAIL OTP TABLE
-- ========================================

CREATE TABLE "EmailOtps"
(
    "EmailOtpId" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "Otp" TEXT NOT NULL,
    "CreatedAt" TIMESTAMPTZ NOT NULL,
    "ExpiryTime" TIMESTAMPTZ NOT NULL,
    "IsUsed" BOOLEAN NOT NULL
);


-- ========================================
-- INDEXES
-- ========================================

CREATE UNIQUE INDEX "IX_Users_Email"
ON "Users" ("Email");

CREATE UNIQUE INDEX "IX_Users_MobileNumber"
ON "Users" ("MobileNumber");

CREATE INDEX "IX_Places_CategoryId"
ON "Places" ("CategoryId");

CREATE INDEX "IX_Businesses_CategoryId"
ON "Businesses" ("CategoryId");

CREATE INDEX "IX_Businesses_OwnerId"
ON "Businesses" ("OwnerId");

CREATE INDEX "IX_BusinessPhotos_BusinessId"
ON "BusinessPhotos" ("BusinessId");

CREATE INDEX "IX_Reviews_BusinessId"
ON "Reviews" ("BusinessId");

CREATE INDEX "IX_Reviews_PlaceId"
ON "Reviews" ("PlaceId");

CREATE INDEX "IX_Reviews_UserId"
ON "Reviews" ("UserId");

CREATE INDEX "IX_ReviewMedias_ReviewId"
ON "ReviewMedias" ("ReviewId");

CREATE INDEX "IX_Favorites_BusinessId"
ON "Favorites" ("BusinessId");

CREATE INDEX "IX_Favorites_PlaceId"
ON "Favorites" ("PlaceId");

CREATE INDEX "IX_Favorites_UserId"
ON "Favorites" ("UserId");

CREATE UNIQUE INDEX "IX_Favorites_UserId_BusinessId"
ON "Favorites" ("UserId", "BusinessId");

CREATE UNIQUE INDEX "IX_Favorites_UserId_PlaceId"
ON "Favorites" ("UserId", "PlaceId");

CREATE INDEX "IX_EmailOtps_UserId_CreatedAt"
ON "EmailOtps" ("UserId", "CreatedAt");


-- ========================================
-- FOREIGN KEY CONSTRAINTS
-- ========================================

ALTER TABLE "Places"
ADD CONSTRAINT "FK_Places_Categories_CategoryId"
FOREIGN KEY ("CategoryId")
REFERENCES "Categories" ("CategoryId")
ON DELETE RESTRICT;

ALTER TABLE "Businesses"
ADD CONSTRAINT "FK_Businesses_Categories_CategoryId"
FOREIGN KEY ("CategoryId")
REFERENCES "Categories" ("CategoryId")
ON DELETE RESTRICT;

ALTER TABLE "Businesses"
ADD CONSTRAINT "FK_Businesses_Users_OwnerId"
FOREIGN KEY ("OwnerId")
REFERENCES "Users" ("Id")
ON DELETE CASCADE;

ALTER TABLE "BusinessPhotos"
ADD CONSTRAINT "FK_BusinessPhotos_Businesses_BusinessId"
FOREIGN KEY ("BusinessId")
REFERENCES "Businesses" ("BusinessId")
ON DELETE CASCADE;

ALTER TABLE "Reviews"
ADD CONSTRAINT "FK_Reviews_Users_UserId"
FOREIGN KEY ("UserId")
REFERENCES "Users" ("Id")
ON DELETE CASCADE;

ALTER TABLE "Reviews"
ADD CONSTRAINT "FK_Reviews_Places_PlaceId"
FOREIGN KEY ("PlaceId")
REFERENCES "Places" ("PlaceId")
ON DELETE CASCADE;

ALTER TABLE "Reviews"
ADD CONSTRAINT "FK_Reviews_Businesses_BusinessId"
FOREIGN KEY ("BusinessId")
REFERENCES "Businesses" ("BusinessId")
ON DELETE CASCADE;

ALTER TABLE "ReviewMedias"
ADD CONSTRAINT "FK_ReviewMedias_Reviews_ReviewId"
FOREIGN KEY ("ReviewId")
REFERENCES "Reviews" ("ReviewId")
ON DELETE CASCADE;

ALTER TABLE "Favorites"
ADD CONSTRAINT "FK_Favorites_Users_UserId"
FOREIGN KEY ("UserId")
REFERENCES "Users" ("Id")
ON DELETE CASCADE;

ALTER TABLE "Favorites"
ADD CONSTRAINT "FK_Favorites_Places_PlaceId"
FOREIGN KEY ("PlaceId")
REFERENCES "Places" ("PlaceId")
ON DELETE CASCADE;

ALTER TABLE "Favorites"
ADD CONSTRAINT "FK_Favorites_Businesses_BusinessId"
FOREIGN KEY ("BusinessId")
REFERENCES "Businesses" ("BusinessId")
ON DELETE CASCADE;

ALTER TABLE "EmailOtps"
ADD CONSTRAINT "FK_EmailOtps_Users_UserId"
FOREIGN KEY ("UserId")
REFERENCES "Users" ("Id")
ON DELETE CASCADE;


-- ========================================
-- CATEGORY SEED DATA
-- ========================================

INSERT INTO "Categories"
    ("CategoryId", "CategoryName", "Icon", "ImageUrl")
VALUES
    (5, 'Salon', '💇', ''),
    (6, 'Gym', '🏋️', ''),
    (7, 'Bakery', '🥐', ''),
    (8, 'Pharmacy', '💊', ''),
    (9, 'Shopping', '🛍️', ''),
    (10, 'Supermarket', '🛒', ''),
    (11, 'Spa', '💆', ''),
    (12, 'Cinema', '🎬', ''),
    (13, 'Electronics', '📱', ''),
    (14, 'Clothing', '👗', ''),
    (15, 'Jewellery', '💍', ''),
    (16, 'Bookstore', '📚', ''),
    (17, 'Pet Store', '🐾', ''),
    (18, 'Travel Agency', '✈️', ''),
    (19, 'Car Service', '🚗', ''),
    (20, 'Real Estate', '🏠', '');